import { useParams, useNavigate } from "react-router-dom"; import { useState, useEffect } from "react"; import { supabase } from "@/integrations/supabase/client"; import { useAuth } from "@/contexts/AuthContext"; import { ArrowLeft, Star, MapPin, Bed, Bath, Maximize, Phone, MessageCircle, CalendarDays, Flag, Share2, Heart, Lock } from "lucide-react"; import { motion } from "framer-motion"; import { toast } from "sonner";
interface DBProperty { id: string; title: string; address: string; area: string; rent: number; rating: number; image_url: string | null; bedrooms: number; bathrooms: number; sqft: number; features: string[]; has_vr: boolean; vr_url: string | null; distance: string | null; phone: string | null; contact_email: string | null; landlord_id: string; }
const gallery = ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"];
const PropertyDetail = () => { const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const { user } = useAuth(); const [p, setP] = useState<DBProperty | null>(null); const [loading, setLoading] = useState(true); const [activeImg, setActiveImg] = useState(0); const [showVR, setShowVR] = useState(false); const [vrLoaded, setVrLoaded] = useState(false); const [isFav, setIsFav] = useState(false); const [role, setRole] = useState<string | null>(null);
useEffect(() => { const getData = async () => { if (!id) return; const { data } = await supabase.from("properties").select("*").eq("id", id).single(); setP(data as DBProperty); setLoading(false); if (user) { const { data: r } = await supabase.from("user_roles").select("role").eq("user_id", user.id).single(); if (r) setRole(r.role); const { data: f } = await supabase.from("favorites").select("id").eq("user_id", user.id).eq("property_id", id).limit(1); if (f?.length) setIsFav(true); } }; getData(); }, [id, user]);
const toggleFav = async () => { if (!user) return toast.error("Sign in required"); if (isFav) { await supabase.from("favorites").delete().eq("user_id", user.id).eq("property_id", id!); setIsFav(false); toast.success("Removed"); } else { await supabase.from("favorites").insert({ user_id: user.id, property_id: id! }); setIsFav(true); toast.success("Saved"); } };
if (loading) return <div className="min-h-screen flex items-center justify-center text-xs font-bold animate-pulse">LOADING...</div>; if (!p) return <div className="min-h-screen flex items-center justify-center text-xs">Property not found.</div>;
const imgs = [p.image_url || gallery[0], ...gallery]; const canVR = user && (role === "tenant" || role === "admin");
return ( <div className="min-h-screen bg-background pb-24"> <header className="sticky top-0 z-40 bg-background/80 backdrop-blur-xl border-b border-border px-4 py-3 flex items-center justify-between"> <button onClick={() => navigate(-1)} className="p-2 bg-secondary rounded-xl"><ArrowLeft className="w-5 h-5"/></button> <span className="text-xs font-black truncate max-w-[150px] uppercase tracking-tighter">{p.title}</span> <div className="flex gap-2"> <button onClick={toggleFav} className="p-2"><Heart className={`w-5 h-5 ${isFav ? "fill-destructive text-destructive" : ""}`}/></button> <button onClick={() => { navigator.clipboard.writeText(window.location.href); toast.success("Link copied"); }} className="p-2"><Share2 className="w-5 h-5"/></button> </div> </header>
<div className="p-4 space-y-6"> <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="relative aspect-video rounded-3xl overflow-hidden bg-secondary"> {showVR && canVR ? ( <div className="w-full h-full"> {!vrLoaded && <div className="absolute inset-0 flex items-center justify-center text-[10px] font-bold">BOOTING VR...</div>} <iframe src={p.vr_url!} className="w-full h-full border-none" allow="xr-spatial-tracking" onLoad={() => setVrLoaded(true)} /> </div> ) : ( <img src={imgs[activeImg]} className="w-full h-full object-cover" /> )} <div className="absolute top-4 left-4"> {p.has_vr ? ( canVR ? ( <button onClick={() => setShowVR(!showVR)} className="bg-primary text-primary-foreground text-[10px] font-black px-3 py-1.5 rounded-full shadow-xl flex items-center gap-1.5"><Box className="w-3 h-3"/> {showVR ? "VIEW PHOTOS" : "ENTER VR"}</button> ) : ( <div className="bg-background/90 backdrop-blur text-[10px] font-bold px-3 py-1.5 rounded-full flex items-center gap-1.5"><Lock className="w-3 h-3"/> TENANT VR ONLY</div> ) ) : ( <div className="bg-orange-500 text-white text-[10px] font-black px-3 py-1.5 rounded-full">NO VR DATA</div> )} </div> </motion.div>
{!showVR && <div className="flex gap-2 overflow-x-auto no-scrollbar"> {imgs.map((img, i) => ( <button key={i} onClick={() => setActiveImg(i)} className={`w-16 h-12 rounded-xl overflow-hidden border-2 flex-shrink-0 ${i === activeImg ? "border-primary" : "border-transparent opacity-50"}`}><img src={img} className="w-full h-full object-cover"/></button> ))} </div>}
<div className="space-y-1"> <div className="flex justify-between items-start"> <h1 className="text-2xl font-black tracking-tighter">{p.title}</h1> <div className="flex items-center gap-1 text-orange-500 font-bold text-sm"><Star className="w-4 h-4 fill-current"/>{p.rating}</div> </div> <p className="text-xs text-muted-foreground flex items-center gap-1"><MapPin className="w-3 h-3"/>{p.address}</p> <p className="text-xl font-black text-primary mt-2">₹{p.rent.toLocaleString()}<span className="text-xs font-medium text-muted-foreground"> /mo</span></p> </div>
<div className="grid grid-cols-3 gap-2"> {[{i:Bed, v:p.bedrooms, l:"Beds"}, {i:Bath, v:p.bathrooms, l:"Baths"}, {i:Maximize, v:p.sqft, l:"SqFt"}].map((s, idx) => ( <div key={idx} className="bg-card border border-border p-3 rounded-2xl text-center"> <s.i className="w-4 h-4 mx-auto mb-1 text-primary"/> <p className="text-sm font-black">{s.v}</p> <p className="text-[10px] text-muted-foreground uppercase">{s.l}</p> </div> ))} </div>
<div className="grid grid-cols-3 gap-2"> <button onClick={() => window.open(`tel:${p.phone}`)} className="bg-primary text-primary-foreground py-4 rounded-2xl flex flex-col items-center gap-1 font-bold text-[10px]"><Phone className="w-4 h-4"/> CALL</button> <button className="bg-secondary py-4 rounded-2xl flex flex-col items-center gap-1 font-bold text-[10px]"><MessageCircle className="w-4 h-4"/> CHAT</button> <button className="bg-secondary py-4 rounded-2xl flex flex-col items-center gap-1 font-bold text-[10px]"><CalendarDays className="w-4 h-4"/> VISIT</button> </div> </div> </div> ); }; export default PropertyDetail;