// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded credentials for RentifyX project
const SUPABASE_URL = "https://rwoswpxrxtctyzzejpzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3b3N3cHhyeHRjdHl6emVqcHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzMTEwNTEsImV4cCI6MjA4OTg4NzA1MX0.JzZCK9QyEKkb4yiDp_7e8IZYwkFL4W3z2Mkz8JhfNT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});